version: "3.9"

services:
  web:
    container_name: offer-api-web
    build:
      context: ./app
    command: "uvicorn main:app --reload --host 0.0.0.0 --port ${WEB_INT_PORT}"
    volumes:
      - ./app:/app
    ports:
      - "${WEB_EXT_PORT}:${WEB_INT_PORT}"
    environment:
      - REDIS_BROKER_URL=${REDIS_BROKER_URL}
      - REDIS_RESULT_BACKEND=${REDIS_RESULT_BACKEND}
      - MONGODB_URL=${MONGODB_URL}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - API_KEY_NAME=${API_KEY_NAME}
      - API_KEY=${API_KEY}
      - TIMEOUT_SECONDS=${TIMEOUT_SECONDS}
    depends_on:
      - redis
      - mongodb

  redis:
    container_name: offer-api-redis
    image: redis:7

  worker:
    container_name: offer-api-worker
    build:
      context: ./app
    command: celery -A celery_app worker --loglevel=info
    volumes:
      - ./app:/usr/src/app
    environment:
      - REDIS_BROKER_URL=${REDIS_BROKER_URL}
      - REDIS_RESULT_BACKEND=${REDIS_RESULT_BACKEND}
      - MONGODB_URL=${MONGODB_URL}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - TIMEOUT_SECONDS=${TIMEOUT_SECONDS}
    depends_on:
      - redis

  mongodb:
    container_name: offer-api-mongodb
    image: mongo:5
    ports:
      - "${MONGODB_EXT_PORT}:${MONGODB_INT_PORT}"
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    command:
      mongod --quiet
