version: "3.9"

services:
  web:
    container_name: offer-api-web
    build:
      context: ./app
    command: "uvicorn main:app --reload --host 0.0.0.0 --port ${WEB_INT_PORT}"
    volumes:
      - ./app:/app
    ports:
      - "${WEB_EXT_PORT}:${WEB_INT_PORT}"
    environment:
      - REDIS_BROKER_URL=${REDIS_BROKER_URL}
      - REDIS_RESULT_BACKEND=${REDIS_RESULT_BACKEND}
    depends_on:
      - redis

  redis:
    container_name: offer-api-redis
    image: redis:7

  worker:
    container_name: offer-api-worker
    build:
      context: ./app
    command: celery -A celery_app worker --loglevel=info
    volumes:
      - ./app:/usr/src/app
    environment:
      - REDIS_BROKER_URL=${REDIS_BROKER_URL}
      - REDIS_RESULT_BACKEND=${REDIS_RESULT_BACKEND}
    depends_on:
      - redis
